version: '3'
services:
  web:
    container_name: family-foto
    image: segelzwerg/family-foto:arm64
    ports:
      - "5050:5000"
    volumes:
      - /media/usb/familyfoto:/app/instance

  # the Prometheus server
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  # Grafana for visualization
  grafana:
    image: grafana/grafana:7.3.6-ubuntu
    user: "docker"
    volumes:
      - /media/usb/grafana:/var/lib/grafana
    ports:
      - 3000:3000