VERSION = '0.6.0'

UPLOADED_PHOTOS_DEST = 'UPLOADED_PHOTOS_DEST'
UPLOADED_PHOTOS_DEST_RELATIVE = 'UPLOADED_PHOTOS_DEST_RELATIVE'

UPLOADED_VIDEOS_DEST = 'UPLOADED_VIDEOS_DEST'
UPLOADED_VIDEOS_DEST_RELATIVE = 'UPLOADED_VIDEOS_DEST_RELATIVE'

# User Levels
ADMIN_LEVEL = 0
USER_LEVEL = 1
GUEST_LEVEL = 2

# Workers
MAX_UPLOAD_WORKERS = 3
