UPLOADED_PHOTOS_DEST = 'UPLOADED_PHOTOS_DEST'
UPLOADED_PHOTOS_DEST_RELATIVE = 'UPLOADED_PHOTOS_DEST_RELATIVE'

UPLOADED_VIDEOS_DEST = 'UPLOADED_VIDEOS_DEST'
UPLOADED_VIDEOS_DEST_RELATIVE = 'UPLOADED_VIDEOS_DEST_RELATIVE'

RESIZED_DEST = 'RESIZED_DEST'
RESIZED_DEST_RELATIVE = 'RESIZED_DEST_RELATIVE'

# User Levels
ADMIN_LEVEL = 0
USER_LEVEL = 1
GUEST_LEVEL = 2
