name: Python Check

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-verion: [3.6, 3.7, 3.8]
      fail-fast: false
      max-parallel: 4
      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Python Pylint Github Action
        run: |
          pylint --rcfile=.pylintrc -j 2 family_foto
          
      - name: Python Pytest with Coverage
        run: |
          pytest --cov=./family_foto --cov-report=xml
      - name: Upload to codecoverage
        uses: codecov/codecov-action@v1.0.6
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
